apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-backend
spec:
  selector:
    matchLabels:
      app: springboot-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-backend
    spec:
      containers:
      - name: springboot-backend
        image: krmp-d2hub-idock.9rum.cc/dev-test/repo_70d8bdbd6b5e
        env:
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: db_url
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: db_username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: db_password
          - name: DB_DRIVER
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: db_driver
        ports:
        - containerPort: 8080
