# springboot-backend 서비스 설정 (변경 없음)
apiVersion: v1
kind: Service
metadata:
  name: springboot-backend
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: krampoline

---
# mysql Headless Service 설정
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None  # Headless Service로 설정
  selector:
    app: mysql  # StatefulSet의 app 라벨과 일치시킴
